[package]
name = "yash-builtin"
version = "0.1.0"
authors = ["WATANABE Yuki <magicant@wonderwand.net>"]
edition = "2018"
description = "Implementation of the built-in utilities of yash"
# documentation = "https://yash.osdn.jp/doc/"
# readme = "README.md"
# homepage = "https://yash.osdn.jp/"
repository = "https://github.com/magicant/yash-rs"
license = "GPL-3.0-or-later"
# license-file = "../LICENSE"
keywords = ["posix", "shell"]
categories = ["command-line-utilities", "parser-implementations"]
publish = false

[dependencies]
yash-core = { path = "../yash-core", version = "0.1.0" }
