[package]
name = "yash-semantics"
version = "0.1.0"
authors = ["WATANABE Yuki <magicant@wonderwand.net>"]
edition = "2021"
rust-version = "1.58.0"
description = "Yash shell language semantics"
# documentation = "https://yash.osdn.jp/doc/"
# readme = "README.md"
# homepage = "https://yash.osdn.jp/"
repository = "https://github.com/magicant/yash-rs"
license = "GPL-3.0-or-later"
# license-file = "../LICENSE"
keywords = ["posix", "shell"]
categories = ["command-line-utilities"]
publish = false

[dependencies]
async-trait = "0.1.56"
yash-arith = { path = "../yash-arith", version = "0.1.0" }
yash-env = { path = "../yash-env", version = "0.1.0" }
yash-fnmatch = { path = "../yash-fnmatch", version = "1.0.0" }
yash-syntax = { path = "../yash-syntax", version = "0.5.0" }

[dev-dependencies]
assert_matches = "1.5.0"
futures-executor = "0.3.23"
futures-util = "0.3.23"
itertools = "0.10.3"
