[package]
name = "yash-env"
version = "0.1.0"
authors = ["WATANABE Yuki <magicant@wonderwand.net>"]
edition = "2021"
rust-version = "1.56.0"
description = "Yash shell execution environment interface"
# documentation = "https://yash.osdn.jp/doc/"
# readme = "README.md"
# homepage = "https://yash.osdn.jp/"
repository = "https://github.com/magicant/yash-rs"
license = "GPL-3.0-or-later"
# license-file = "../LICENSE"
keywords = ["posix", "shell"]
categories = ["command-line-utilities"]
publish = false

[dependencies]
annotate-snippets = "0.9.1"
async-trait = "0.1.56"
either = "1.6.1"
enumset = "1.0.10"
futures-util = "0.3.21"
itertools = "0.10.3"
nix = "0.23.1"
slab = "0.4.6"
yash-quote = { path = "../yash-quote", version = "1.0.0" }
yash-syntax = { path = "../yash-syntax", version = "0.4.0" }

[dev-dependencies]
assert_matches = "1.5.0"
futures-executor = "0.3.21"
futures-util = { version = "0.3.21", features = ["channel"] }
