[package]
name = "yash-env"
version = "0.1.0"
authors = ["WATANABE Yuki <magicant@wonderwand.net>"]
edition = "2018"
description = "Yash shell execution environment interface"
# documentation = "https://yash.osdn.jp/doc/"
# readme = "README.md"
# homepage = "https://yash.osdn.jp/"
repository = "https://github.com/magicant/yash-rs"
license = "GPL-3.0-or-later"
# license-file = "../LICENSE"
keywords = ["posix", "shell"]
categories = ["command-line-utilities"]
publish = false

[dependencies]
either = "1.6.1"
nix = { version = "0.21.0", optional = true }
yash-syntax = { path = "../yash-syntax", version = "0.1.0" }

[features]
default = ["real-system"]
real-system = ["nix"]
