[package]
name = "yash-env"
version = "0.1.0"
authors = ["WATANABE Yuki <magicant@wonderwand.net>"]
edition = "2021"
rust-version = "1.56.0"
description = "Yash shell execution environment interface"
# documentation = "https://yash.osdn.jp/doc/"
# readme = "README.md"
# homepage = "https://yash.osdn.jp/"
repository = "https://github.com/magicant/yash-rs"
license = "GPL-3.0-or-later"
# license-file = "../LICENSE"
keywords = ["posix", "shell"]
categories = ["command-line-utilities"]
publish = false

[dependencies]
async-trait = "0.1.52"
either = "1.6.1"
futures-util = "0.3.19"
itertools = "0.10.3"
nix = "0.23.1"
yash-syntax = { path = "../yash-syntax", version = "0.2.0" }

[dev-dependencies]
assert_matches = "1.5.0"
futures-executor = "0.3.19"
futures-util = { version = "0.3.19", features = ["channel"] }
